public class Main {
    public static void main(String[] args) {
        Fish fish1 = new Fish();
        fish1.setName("Карп");
        fish1.setType("Семейство Карповых");
        fish1.setSize(25);
        fish1.setColor("Желто-зеленый");
        System.out.println("Имя: "+fish1.getName());
        System.out.println("Тип: "+fish1.getType());
        System.out.println("Размеры: "+fish1.getSize()+"см");
        System.out.println("Цвет: "+fish1.getColor());
        Fish fish2 = new Fish();
        fish2.setName("Щука");
        fish2.setType("Семейство Щуковых");
        fish2.setSize(100);
        fish2.setColor("Серо-зеленые полосы");
        System.out.println();
        System.out.println("Имя: "+fish2.getName());
        System.out.println("Тип: "+fish2.getType());
        System.out.println("Размеры: "+fish2.getSize()+"см");
        System.out.println("Цвет: "+fish2.getColor());
        Dog dog1 = new Dog();
        dog1.setName("Берни");
        dog1.setType("Чихуахуа");
        dog1.setAge(2);
        dog1.setColor("Коричневый");
        System.out.println();
        System.out.println("Имя: "+dog1.getName());
        System.out.println("Тип: "+dog1.getType());
        System.out.println("Возраст: "+dog1.getAge()+"года");
        System.out.println("Цвет: "+dog1.getColor());
        Dog dog2 = new Dog();
        dog2.setName("Рекс");
        dog2.setType("Немецкая овчарка");
        dog2.setAge(3);
        dog2.setColor("Черно-коричневый");
        System.out.println();
        System.out.println("Имя: "+dog2.getName());
        System.out.println("Тип: "+dog2.getType());
        System.out.println("Возраст: "+dog2.getAge()+"года");
        System.out.println("Цвет: "+dog2.getColor());
        Parrot parrot1 = new Parrot();
        parrot1.setName("Петруша");
        parrot1.setType("волнистый попугай");
        parrot1.setSize(13);
        parrot1.setColor("Желто-зеленый");
        System.out.println();
        System.out.println("Имя: "+parrot1.getName());
        System.out.println("Тип: "+parrot1.getType());
        System.out.println("Размер: "+parrot1.getSize()+"см");
        System.out.println("Цвет: "+parrot1.getColor());
        Parrot parrot2 = new Parrot();
        parrot2.setName("Чика");
        parrot2.setType("Розелла");
        parrot2.setSize(25);
        parrot2.setColor("сочетание красного,синего,желтого");
        System.out.println();
        System.out.println("Имя: "+parrot2.getName());
        System.out.println("Тип: "+parrot2.getType());
        System.out.println("Размер: "+parrot2.getSize()+"см");
        System.out.println("Цвет: "+parrot2.getColor());
        Cat cat1 = new Cat();
        cat1.setName("Tom");
        cat1.setType("Мейн-кун");
        cat1.setAge(3);
        cat1.setColor("Черно-белые полосы");
        System.out.println();
        System.out.println("Имя: "+cat1.getName());
        System.out.println("Тип: "+cat1.getType());
        System.out.println("Возраст: "+cat1.getAge()+"года");
        System.out.println("Цвет: "+cat1.getColor());
        Cat cat2 = new Cat();
        cat2.setName("Белок");
        cat2.setType("Сибирская");
        cat2.setAge(1);
        cat2.setColor("Белый");
        System.out.println();
        System.out.println("Имя: "+cat2.getName());
        System.out.println("Тип: "+cat2.getType());
        System.out.println("Возраст: "+cat2.getAge()+"год");
        System.out.println("Цвет: "+cat2.getColor());
    }
}